PmiOfficial/Models/UserInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PmiOfficial.Models
{
    public class UserInfo
    {
        public string Name { get; set; }
        public int Id { get; set; }
        public bool IsAuthenticated { get; set; }
    }

    public class UserInfoHub
    {
        public string Name { get; set; }

        public DateTime ConnectedTime { get; set; }

        public HashSet<string> ConnectionsIdList = new HashSet<string>();

        public int UserId { get; set; }
    }
}

PmiOfficial/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PmiOfficial.Filters;
using PmiOfficial.Models;

namespace PmiOfficial.Controllers
{
    public class LoginController : Controller
    {
        [AllowAnonymous]
        public ActionResult Index(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

    }
}

PmiOfficial/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PmiOfficial.Filters;

namespace PmiOfficial.Controllers
{
    public class RegistrationController : Controller
    {
        //
        // GET: /Registration/
        public ActionResult Index()
        {
            return View();
        }
	}
}

PmiOfficial/Controllers/StatisticsController.cs
using System;
using System.Web.Mvc;
using DataAccess.DAO;
using Services.Statistics;

namespace PmiOfficial.Controllers
{
    //[Authorize] - публічно доступне через проблеми з реєстрацією
    public class StatisticsController : Controller
    {
        private readonly IStatService _statService;

        public StatisticsController()
        {
            _statService = new StatService(new EventDAO(), new UserDAO());
        }

        public ActionResult Index()
        {
            var userStats = _statService.GetUserBirthdayStats();

            ViewBag.UserStatsLabels = String.Join(", ", userStats.Keys);;
            ViewBag.UserStatsData = String.Join(", ", userStats.Values);

            var eventStats = _statService.GetHourlyEventStats();

            ViewBag.EventStatsLabels = String.Join(", ", eventStats.Keys);
            ViewBag.EventStatsData = String.Join(", ", eventStats.Values);

            return View();

        }
    }
}

PmiOfficial/Controllers/UserProfileController.cs
using System.Collections.Generic;
using System.Text;
using System.Web;
using System.Web.Mvc;
using DataAccess.DAO;
using Microsoft.AspNet.Identity;
using PmiOfficial.Models;
using Services;
using Services.DTO;
using Services.ImageServices;
using DataAccess.Entities;
using System.Linq;

namespace PmiOfficial.Controllers
{
    public class UserProfileController : Controller
    {
        public IUserService UserService;
        public IImageService _imagesService;
        public IUsefulLinkService _usefulLinkService;
        public UserProfileController()
        {
            UserService = new UserService(new UserDAO());
            _imagesService = new ImageService();
            _usefulLinkService = new UsefulLinkService(new UsefulLinkDAO());
        }

        // GET: UserProfile
        public ActionResult Index(int userId)
        {
            ImageDAO imageDAO = new ImageDAO();

            User user = UserService.Get(userId);
            ViewBag.UserId = user.Id;
            ViewBag.User = user;
            List<UsefulLink> list = _usefulLinkService.ReadAll();
            if (list.Count == 0)
            {
                ViewBag.UsefulLinks = new List<UsefulLink>();
            }
            else
            {
                ViewBag.UsefulLinks = from x in list
                                           where x.OwnerUserID == user.Id
                                           select x;
            }
            ViewBag.DefaultUsefulLinkImage = UsefulLinkService.DEFAULT_USEFUL_LINK_IMAGE_URL;
            ViewBag.User.Hobbies = "hobbies";
            ViewBag.User.Plans = new Dictionary<string, List<string>>{ { "Monday", new List<string> { "Rest", "ЧМ" } },
                    { "Tuesday", new List<string> {"Movie" } }, {"Wednesday", new List<string>()}, {"Thursday", new List<string>() }, {"Friday", new List<string>()}};

            if (user.ImageId != 0)
            {
                var image = _imagesService.Get(user.ImageId);
                if (!string.IsNullOrEmpty(image.PathToLocalImage))
                {
                    ViewBag.UserImage = ConvertLocalServerPathToUrl(image.PathToLocalImage);
                }
            }

            return View();
        }

        [HttpPost]
        public ActionResult Edit(EditUserDTO userDto, System.Web.HttpPostedFileBase imageFile)
        {
            userDto.ImageFile = imageFile;
            UserService.Edit(userDto, HttpContext.Server);

            return RedirectToAction("Index", new { userId = userDto.Id });
        }


        public PartialViewResult UserInfo()
        {
            UserInfo info = new UserInfo
            {
                Id = User.Identity.GetUserId<int>(),
                Name = User.Identity.Name,
                IsAuthenticated = User.Identity.IsAuthenticated
            };
            return PartialView("UserInfo", info);
        }

        private string ConvertLocalServerPathToUrl(string localPath)
        {
            var url = new StringBuilder(localPath);

            url.Replace(@"\", @"/");
            int index = localPath.IndexOf(ImageService.LOCAL_FOLDER_TO_SAVE_IMAGES);

            url.Remove(0, index);

            url.Insert(0, @"~/");

            return url.ToString();
        }
    }
}

PmiOfficial/Views/Shared/UserInfo.cshtml
@model PmiOfficial.Models.UserInfo
@if (Model.IsAuthenticated)
{
    <li><a href="@Url.Action("Index", "UserProfile", new { userID = Model.Id })">Hello @Model.Name</a></li>
    <li><a href="/logout">LogOut</a></li>
    
   
    <div id="globalChat" class="ui-widget-content panel panel-primary draggable" rel="0">
        <div class="header panel-heading">
            <span id="imgDelete" class="glyphicon glyphicon-remove pull-right"></span>
            <span class="selText" rel="0"> All users </span>
        </div>
   
            <div id="divMessage" class="messageArea panel-body">

            </div>
            <div class="buttonBar panel-footer form-inline">
                <input id="globalMessage" class="msgText form-control" type="text" />
                <button id="globalSendMessage" class="btn btn-primary"> Send </button>
            </div>
        </div>

    <div id="chatBody" class="panel panel-primary panel-body well" style="display: none; position: fixed; bottom: 60px; left: 0px;">
        <div id="header"></div>
        <div id="inputForm" class="form-group form-inline">
            <input type="text" id="message" class="form-control" />
            <input type="button" class="btn btn-default" id="sendmessage" value="Send" />
        </div>
        <div id="chatroom" style="max-height: 400px; max-width: 300px;overflow-y: scroll"></div>

        <div id="chatusers">
            <p><b>Amount of users: <span id="userCount"></span></b></p>
        </div>
    </div>
    <div id="divContainer">
        <div id="chatMultUsersDiv" class="ui-widget-content panel panel-primary chatMultipleUsers">
            <div class="title header panel-heading">
                Logged Users
            </div>
            <div id="divusers" class="users">
                <a id="globalTitle" class="user">Global chat</a>
            </div>
        </div>
        <div id="toggleChatButtonDiv" class="toggleButton">
            <button id="toggleChatButton" class="btn btn-default">
                <span class="glyphicon glyphicon-list"></span>
            </button>
        </div>
        <input id="chatHhUserID" type="hidden" />
        <input id="chatHhUserName" type="hidden" />
    </div>
    <input id="hdId" type="hidden" />
    <input id="username" type="hidden" />

    <script>
        userName = "@Model.Name";
        loggedUserID = @Model.Id;

    </script>
  
}
else
{
    <li>@Html.ActionLink("Sign in", "Index", "Login", new { area = "" }, null)</li>
    <li>@Html.ActionLink("Sign up", "Index", "Registration", new { area = "" }, null)</li>
    
}

PmiOfficial/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="~/Content/jquery.datepick.css">
    <link rel="stylesheet" type="text/css" href="~/Content/themes/base/all.css">
    <link rel="stylesheet" type="text/css" href="~/Content/Chat.css" />
    @Styles.Render("~/Content/css")

    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("AddToLayout", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PMI 31", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Website Statistics", "Index", "Statistics", new { area = "" }, null)</li>
                    @Html.Action("UserInfo", "UserProfile")
                </ul>
            </div>
        </div>
    </div>
    <!--class="container body-content"-->
    <div>
        @RenderBody()
        <hr />
        <footer align="center">
            <p class="copy_rigths">&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    <!-- Fetch the image addition script -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/signalr/hubs"></script>
    <script src="~/Scripts/globalChat.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>